rejection_types: 
  - 'fields'
  - 'leader'

processor_types: 
  - 'concatenate' 
  - 'constant'
  - "extract"
  - 'matches'
  - 'missing_all'
  - 'not_matches'
  - 'replace'
  - 'specific_entry'
  - 'truncate'

# Redis host and port are required
redis_host: '127.0.0.1'
redis_port: 6379