extends: 'PAPR'

import:
  marc:
    local_catalog_ids:   ['004']
    oclc_numbers:        ['035$a']
    location_codes:      ['945$l']
    holding_statements:  ['945$u', '866$a']
    holding_years:       ['945$u', '866$a']
    holding_record_ids:  ['035$a', '866$a']

  # -------------------------------------------------------------
  split_holdings_on:     ['945$l']

  # -------------------------------------------------------------
  rejection_rules:
    # LDR/05 = d
    leader:
      matches:     '^.{5}[dD]'

    # Missing 004, 022, AND 035
    fields: 
      missing_all: ['004', '035', '022']

  # -------------------------------------------------------------
  conversion_rules:
    # oclc number starts with (OCoLC)
    oclc_numbers:
      matches:            '^\([oO][cC][oO][lL][cC]\)'

    # holding record ids start with b
    holding_record_ids:
      matches:            '^[bB]'

    holding_years:
      extract:               '\d{4}'

export:
  # -------------------------------------------------------------
  conversion_rules:
    oclc_numbers:
      specific_entry:     {'position': 'first'}

    subjects:
      specific_entry:     {'position': 'first'}

    holding_statements:
      concatenate:        {delimiter: ', '}