extends: 'PAPR'

import:
  marc:
    local_catalog_ids:   ['001']
    oclc_numbers:        ['035$a']
    location_codes:      ['852$c']
    holding_statements:  ['863$i', '866$a', '863$a']
    holding_years:       ['863$i', '866$a', '863$a']
    holding_record_ids:  ['978$a']

  # -------------------------------------------------------------
  record_identifier:     'local_catalog_ids'

  # -------------------------------------------------------------
  split_holdings_on:     ['852$c']

  # -------------------------------------------------------------
  rejection_rules:
    # LDR/05 = d OR LDR/06-07 != as
    leader:
      matches:     '^.{5}[dD]'
      not_matches: '^.{6}[aA][sS]'

    # Missing 001, 022, AND 035
    fields: 
      missing_all: ['001', '035', '022']

  # -------------------------------------------------------------
  conversion_rules:
    # oclc number starts with (OCoLC) or matches ocm/ocn
    oclc_numbers:
      matches:            '^\(?[oO][cC]((oLC)|([mMnN]))\)?'

    holding_years:
      extract:               '\d{4}'

export:
  # -------------------------------------------------------------
  conversion_rules:
    oclc_numbers:
      specific_entry:     {'position': 'first'}

    subjects:
      specific_entry:     {'position': 'first'}

    holding_statements:
      specific_entry:     {'position': 'first', 'order': ['863$i', '866$a', '863$a']}