extends: 'PAPR'

import:
  marc:
    local_catalog_id:    ['001']
    oclc_numbers:        ['035$a']
    location_code:       ['852$c']
    holdings_statement:  ['863$i', '866$a', '863$a']

  # -------------------------------------------------------------
  record_identifier:     'local_catalog_id'

  # -------------------------------------------------------------
  split_holdings_on:     ['852$c']

  # -------------------------------------------------------------
  rejection_rules:
    # LDR/05 = d OR LDR/06-07 != as
    leader:
      matches:     '^.{5}[dD]'
      not_matches: '^.{6}[aA][sS]'

    # Missing 001, 022, AND 035
    fields: 
      missing_all: ['001', '035', '022']

  # -------------------------------------------------------------
  conversion_rules:
    # oclc number starts with (OCoLC) or matches ocm/ocn
    oclc_numbers:
      matches:            '^\(?[oO][cC]((oLC)|([mMnN]))\)?'

export:
  # -------------------------------------------------------------
  conversion_rules:
    oclc_numbers:
      specific_entry:     {'position': 'first'}

    subjects:
      specific_entry:     {'position': 'first'}

    holdings_statement:
      specific_entry:     {'position': 'first', 'order': ['863$i', '866$a', '863$a']}