# -------------------------------------------------------------
import:

  # -------------------------------------------------------------
  conversion_rules:
    # remove all non-printable characters
    ALL:
      replace:             {find: '^[:print:]', value: ''}
