extends: 'PAPR'

import:
  marc:
    local_catalog_ids:   ['001']
    oclc_numbers:        ['035$a']
    location_codes:      ['852$b']
    holding_statements:  ['866$a', '863$i', '863$a', '852$z']
    holding_years:       ['866$a', '863$i', '863$a', '852$z']
    holding_record_ids:  ['035$a', '866$a']

  # -------------------------------------------------------------
  merge_records:         true

  # -------------------------------------------------------------
  split_holdings_on:     ['852$b']

  # -------------------------------------------------------------
  rejection_rules:
    # LDR/05 = d
    leader:
      matches:     '^.{5}[dD]'

    # Missing 004, 022, AND 035
    fields: 
      missing_all: ['001', '035', '022']

  # -------------------------------------------------------------
  conversion_rules:
    # oclc number starts with (OCoLC)
    oclc_numbers:
      matches:            '^\([oO][cC][oO][lL][cC](\-[mM])?\)(-[iI])?'

    holding_years:
      extract:               '\d{4}'

export:
  # -------------------------------------------------------------
  conversion_rules:
    oclc_numbers:
      specific_entry:     {'position': 'first'}

    subjects:
      specific_entry:     {'position': 'first'}

    holding_statements:
      concatenate:        {delimiter: ', '}